lang: de-DE

project:
  type: book
  output-dir: _output/book/

execute:
  cache: true

bibliography: bcd-baustein-sicherheitsanalyse.bib

book:
  title: "Anwendungsbaustein Sicherheitsanalyse"
  author:
    - Lukas Arnold
    - Simone Arnold
    - Florian Bagemihl
    - Matthias Baitsch
    - Marc Fehr
    - Franca Hollmann
    - Maik Poetzsch
    - Sebastian Seipel
  date: today
  repo-url: "https://github.com/bausteine-der-datenanalyse/a-sicherheitsanalyse"
  repo-actions: [source]
  favicon: "bilder/favicon_bcd_new.svg"
  sidebar:
    title: "Anwendungsbaustein Sicherheitsanalyse"
    logo: "bilder/logo_bcd_new.svg"
  chapters:
    - index.qmd
    - aufgabenstellung.qmd
    - musterloesung.qmd
  downloads: 
    - pdf

format:
  html:
    theme: cosmo
    lang: de
    toc: true
    toc-depth: 4
    format-links: 
      - pdf
  pdf:
    listings: true
    include-in-header:
      text: |
        \usepackage{xcolor}
        \definecolor{codebg}{HTML}{F0F0F0}
        \lstset{
          breaklines=true,
          breakatwhitespace=false,
          basicstyle=\ttfamily\small,
          backgroundcolor=\color{codebg}
        }
    fig-width: 6
    fig-height: 4