project:
  type: book
  output-dir: _output/book/

execute:
  cache: false
  warning: false

book:
  title: "Anwendungsbaustein Sicherheitsanalyse"
  author:
    - Lukas Arnold
    - Simone Arnold
    - Florian Bagemihl
    - Matthias Baitsch
    - Marc Fehr
    - Franca Hollmann
    - Maik Poetzsch
    - Sebastian Seipel
  date: today
  language: de-DE
  repo-url: "https://github.com/bausteine-der-datenanalyse/a-sicherheitsanalyse"
  repo-actions: [source]
  favicon: "bilder/favicon_bcd_new.svg"
  sidebar:
    title: "Anwendungsbaustein Sicherheitsanalyse"
    logo: "bilder/logo_bcd_new.svg"
  chapters:
    - index.qmd
    - aufgabenstellung.qmd
    - musterloesung.qmd
    - musterloesung-erlaeutert.qmd

format:
  html:
    theme: cosmo
    lang: de
    toc: true
    toc-depth: 4


